aws_region           = "eu-west-1"
project_name         = "bookreview"
environment          = "dev"
vpc_cidr             = "90.0.0.0/16"
public_subnet_1_cidr = "90.0.1.0/24"
public_subnet_2_cidr = "90.0.2.0/24"
private_subnet_1_cidr = "90.0.10.0/24"
private_subnet_2_cidr = "90.0.11.0/24"
instance_type        = "t3.small"
ssh_public_key_path = "/home/lumanex/.ssh/bookapp_aws.pub"
db_instance_class    = "db.t3.micro"
db_name              = "bookreview"
db_username          = "bookadmin"
db_password          = "Geology5565021"  # Change this or use variable

