trigger:
  branches:
    include:
    - main
  paths:
    include:
    - modules/*
    - environments/dev/*

pool:
  vmImage: 'SelfHostedAgent'  # or name: 'Default' for self-hosted

variables:
  terraformVersion: '1.5.7'
  workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'

stages:
- stage: Infrastructure
  displayName: 'Deploy AWS Infrastructure'
  jobs:
  - job: TerraformDeploy
    displayName: 'Terraform Apply'
    steps:
    
    # Install Terraform using script
    - script: |
        echo "Installing Terraform version $(terraformVersion)..."
        wget -O terraform.zip https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform --version
        echo "Terraform installed successfully"
      displayName: 'Install Terraform'
    
    # Download SSH public key from Secure Files
    - task: DownloadSecureFile@1
      name: sshPublicKey
      displayName: 'Download SSH Public Key'
      inputs:
        secureFile: 'bookapp_aws.pub'
    
    # Prepare SSH key directory
    - script: |
        mkdir -p $(workingDirectory)/keys
        cp $(sshPublicKey.secureFilePath) $(workingDirectory)/keys/bookapp_aws.pub
        echo "SSH key prepared at: $(workingDirectory)/keys/bookapp_aws.pub"
        ls -la $(workingDirectory)/keys/
      displayName: 'Prepare SSH Key'
    
    # Set AWS credentials as environment variables
    - script: |
        echo "Setting AWS environment variables..."
        echo "AWS Region: $(AWS_REGION)"
      displayName: 'Configure AWS Credentials'
    
    # Terraform Init
    - script: |
        cd $(workingDirectory)
        echo "Initializing Terraform..."
        terraform init
      displayName: 'Terraform Init'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_REGION)
    
    # Terraform Validate
    - script: |
        cd $(workingDirectory)
        echo "Validating Terraform configuration..."
        terraform validate
      displayName: 'Terraform Validate'
    
    # Terraform Plan
    - script: |
        cd $(workingDirectory)
        echo "Running Terraform plan..."
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_REGION)
        TF_VAR_db_password: $(DB_PASSWORD)
    
    # Terraform Apply
    - script: |
        cd $(workingDirectory)
        echo "Applying Terraform configuration..."
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_REGION)
        TF_VAR_db_password: $(DB_PASSWORD)
    
    # Display Terraform Outputs
    - script: |
        cd $(workingDirectory)
        echo "======================================"
        echo "TERRAFORM OUTPUTS - COPY THESE VALUES"
        echo "======================================"
        
        # Save outputs to JSON
        terraform output -json > outputs.json
        
        echo ""
        echo "Frontend Public IP:"
        terraform output -raw frontend_public_ip
        echo ""
        
        echo "Backend Public IP:"
        terraform output -raw backend_public_ip
        echo ""
        
        echo "MySQL Endpoint:"
        terraform output -raw mysql_endpoint
        echo ""
        
        echo "MySQL Address (without port):"
        terraform output -raw mysql_address
        echo ""
        echo "======================================"
        echo ""
        echo "Copy these values to update your ansible inventory!"
      displayName: 'Display Terraform Outputs'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_REGION)
    
    # Publish outputs as artifact (optional but helpful)
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Terraform Outputs'
      inputs:
        PathtoPublish: '$(workingDirectory)/outputs.json'
        ArtifactName: 'terraform-outputs'
      condition: succeeded()
