trigger:
  branches:
    include:
    - main
  paths:
    include:
    - modules/*
    - environments/dev/*

pool:
  name: 'SelfHostedAgent'  # Your self-hosted agent pool or use 'ubuntu-latest'

variables:
  terraformVersion: '1.5.7'
  workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'

stages:
- stage: Infrastructure
  displayName: 'Deploy AWS Infrastructure'
  jobs:
  - job: TerraformDeploy
    displayName: 'Terraform Apply'
    steps:
    
    # Install Terraform
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: $(terraformVersion)
    
    # Download SSH public key from Secure Files
    - task: DownloadSecureFile@1
      name: sshPublicKey
      displayName: 'Download SSH Public Key'
      inputs:
        secureFile: 'bookapp_aws.pub'
    
    # Prepare SSH key directory
    - script: |
        mkdir -p $(System.DefaultWorkingDirectory)/environments/dev/keys
        cp $(sshPublicKey.secureFilePath) $(System.DefaultWorkingDirectory)/environments/dev/keys/bookapp_aws.pub
        echo "SSH key prepared at: $(System.DefaultWorkingDirectory)/environments/dev/keys/bookapp_aws.pub"
      displayName: 'Prepare SSH Key'
    
    # Set AWS credentials as environment variables
    - script: |
        echo "##vso[task.setvariable variable=AWS_ACCESS_KEY_ID]$(AWS_ACCESS_KEY_ID)"
        echo "##vso[task.setvariable variable=AWS_SECRET_ACCESS_KEY]$(AWS_SECRET_ACCESS_KEY)"
        echo "##vso[task.setvariable variable=AWS_DEFAULT_REGION]$(AWS_REGION)"
      displayName: 'Set AWS Environment Variables'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_REGION: $(AWS_REGION)
    
    # Terraform Init
    - script: |
        cd $(workingDirectory)
        terraform init
      displayName: 'Terraform Init'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_REGION)
    
    # Terraform Validate
    - script: |
        cd $(workingDirectory)
        terraform validate
      displayName: 'Terraform Validate'
    
    # Terraform Plan
    - script: |
        cd $(workingDirectory)
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_REGION)
        TF_VAR_db_password: $(DB_PASSWORD)
    
    # Terraform Apply
    - script: |
        cd $(workingDirectory)
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_REGION)
        TF_VAR_db_password: $(DB_PASSWORD)
    
    # Display Terraform Outputs
    - script: |
        cd $(workingDirectory)
        echo "======================================"
        echo "TERRAFORM OUTPUTS - COPY THESE VALUES"
        echo "======================================"
        terraform output -json > outputs.json
        
        echo ""
        echo "Frontend Public IP:"
        terraform output -raw frontend_public_ip
        echo ""
        
        echo "Backend Public IP:"
        terraform output -raw backend_public_ip
        echo ""
        
        echo "MySQL Endpoint:"
        terraform output -raw mysql_endpoint
        echo ""
        
        echo "MySQL Address (without port):"
        terraform output -raw mysql_address
        echo ""
        echo "======================================"
      displayName: 'Display Terraform Outputs'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_REGION)
    
    # Publish outputs as artifact (optional)
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Terraform Outputs'
      inputs:
        PathtoPublish: '$(workingDirectory)/outputs.json'
        ArtifactName: 'terraform-outputs'